### ISSUE TITLE
Cbmc compatibility

### ISSUE THREAD

**Issue by arey0pushpa** [dtrebbien/Z3#3]
I'm using a basic cbmc program 

int main() 
{ 
   int a[10]; 
   __CPROVER_assert(__CPROVER_forall 
                    {unsigned int i; 
                    (i >= 0 && i < 10) ==> a[i] < 0}, 
                    "Assert_Forall"); 
   __CPROVER_assert(__CPROVER_forall 
                    {unsigned int i; 
                    __CPROVER_exists 
                    {unsigned int j; 
                    (i>=0 && i<10 && j>=0 && j<10) ==> a[i] > a[j]}}, 
                    "Assert_Forall_Exists"); 
   return 0; 
} 

$ cbmc --z3 quant5.c 

CBMC version 5.3 64-bit x86_64 linux
Parsing quant5.c
Converting
Type-checking quant5
Generating GOTO Program
Adding CPROVER library
Function Pointer Removal
Partial Inlining
Generic Property Instrumentation
Starting Bounded Model Checking
size of program expression: 34 steps
simple slicing removed 5 assignments
Generated 2 VCC(s), 2 remaining after simplification
Passing problem to SMT2 QF_AUFBV using Z3
converting SSA
Running SMT2 QF_AUFBV using Z3
SMT2 solver returned error message:
	"line 65 column 16: invalid get-value term, term must be ground and must not contain quantifiers"
Runtime decision procedure: 0.025s
decision procedure failed

Is that due to  inner exists ??

 __CPROVER_exists 
                    {unsigned int j; 
                    (i>=0 && i<10 && j>=0 && j<10) ==> a[i] > a[j]}

**Comment by dtrebbien** [comment]
I have not used CBMC before, so I am not sure what the problem might be.  You might try asking your question in the cprover-support Google Group:
https://groups.google.com/forum/#!forum/cprover-support

Also, please note that this fork is unmaintained.  Please see the Z3 project's repository on GitHub:
https://github.com/Z3Prover/z3

**Comment by arey0pushpa** [comment]
Sorry . Have asked question in wrong place. Corrected my mistakes in mins. Got reply from both forum. Thanks. take care.
